import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Header from "@/components/header/Header";
import { Climate_Crisis } from "next/font/google";
import Footer from "@/components/footer/Footer";
import TopLinksSection from "@/components/header/headerCompontents/TopLinksSection";
import { Suspense } from "react";
import Loading from "./product/[title]/loading";
import "react-toastify/dist/ReactToastify.css";
import ToastCompontent from "@/utils/ToastCompontent";
import { GoogleAnalytics } from "@next/third-parties/google";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KamShop",
  description: "Generated by create next app",
};

const climateCrisis = Climate_Crisis({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-climate-crisis",
});

const CLERK_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

if (!CLERK_PUBLISHABLE_KEY) {
  throw new Error("Missing clerk key");
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <ClerkProvider publishableKey={CLERK_PUBLISHABLE_KEY}>
        <html lang="en" className={climateCrisis.variable}>
          <body className="flex flex-col min-h-screen">
            <GoogleAnalytics gaId="G-FBNWCD71JM" />
            <ToastCompontent />
            <TopLinksSection />
            <Header />
            <Suspense fallback={<Loading />}>
              <div className="flex-grow">{children}</div>
            </Suspense>
            <Footer />
          </body>
        </html>
      </ClerkProvider>
    </StoreProvider>
  );
}
