import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Header from "@/components/header/Header";
import Head from "next/head";
import { Climate_Crisis } from "next/font/google";
import Footer from "@/components/footer/Footer";
import TopLinksSection from "@/components/header/headerCompontents/TopLinksSection";
import { AnimatePresence } from "framer-motion";
import { Suspense } from "react";
import Loading from "./product/[title]/loading";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ToastCompontent from "@/utils/ToastCompontent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KamShop",
  description: "Generated by create next app",
};

const climateCrisis = Climate_Crisis({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-climate-crisis",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en" className={climateCrisis.variable}>
        <body className="flex flex-col min-h-screen">
          <ToastCompontent />
          <TopLinksSection />
          <Header />
          <Suspense fallback={<Loading />}>
            <div className="flex-grow">{children}</div>
          </Suspense>
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
